### ISSUE TITLE
Not compatible with Webpack 3 ?

### ISSUE THREAD

**Issue by firestar300** [redcatjs/webpack-php-loader#3]
Hi,
The php-loader doesn't fetch my php files to convert to html files. Did I miss something ?

webpack.config.js
```let config = {
  entry: {
    app: ['./assets/css/style.scss', './assets/js/app.js']
  },
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: dev ? '[name].js' : '[name].[chunkhash:8].js'
  },
  watch: dev,
  devtool: dev ? 'source-map' : false,
  module: {
    rules: [
      {
        test: /\.php$/,
        use: 'php-loader'
      },...

**Comment by devthejo** [comment]
Hi,
I've not yet tested it with webpack 3 but instead of

    use: 'php-loader'

try

    use: 'webpack-php-loader'

because this package is webpack-php-loader, php-loader refer to another package
