### ISSUE TITLE
Curious if you think this might be used to make wordpress themes more compatible with webpack templates?

### ISSUE THREAD

**Issue by jcklpe** [redcatjs/webpack-php-loader#5]
I'm having an issue using a webpack plugin for inlining critical css here: https://github.com/GoogleChromeLabs/critters/issues/16

And I think the main issue is that my wp theme is using php and no html so the plugin doesn't know how to grab the html and inline the css. 

If I were running vanilla PHP then I imagine using this to make the php stuff compatible with critters would be fairly straightforward but I don't think it would be possible with Wordpress. Any thoughts on that? I'm a new dev so I don't even really know how to go about pulling apart this problem.

**Comment by devthejo** [comment]
You can effectively try to use this webpack plugin to retrieve the generated code, but I can't say you more on the subject caues I don't use wordpress or critters myself. Good luck

**Comment by jcklpe** [comment]
Thanks!
